package DSA;

public class Js 
{
	public Js()
	{
		System.out.println("let balance=10000;\r\n"
				+ "console.log(\"YOUR CURRENT BALANCE IS \" + \" = \" + balance);\r\n"
				+ "\r\n"
				+ "let withdraw = 1000;\r\n"
				+ "\r\n"
				+ "if(withdraw <= balance)\r\n"
				+ "{\r\n"
				+ "    balance = balance - withdraw;\r\n"
				+ "    console.log(\"WITHDRAW SUCCESSFULL\");\r\n"
				+ "}\r\n"
				+ "else{\r\n"
				+ "    console.log(\"INSUFFECIENT BALANCE\");\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "console.log(\"BALANCE AFTER WITHDRAW\", balance);\r\n"
				+ "console.log(\"---------------\");\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "// By using SWITCH CASE\r\n"
				+ "\r\n"
				+ "let transactiontype =\"\";\r\n"
				+ "\r\n"
				+ "switch(transactiontype){\r\n"
				+ "    \r\n"
				+ "    case \"deposit\":\r\n"
				+ "        balance += 55000;\r\n"
				+ "        console.log(\"BALANCE AFTER DEPOSIT \", balance);\r\n"
				+ "        break;\r\n"
				+ "        \r\n"
				+ "    case \"checkBalance\":\r\n"
				+ "        console.log(\"THIS IS YOUR CURRENT BALANCE \" , balance);\r\n"
				+ "        break;\r\n"
				+ "        \r\n"
				+ "    case \"withdraw\":\r\n"
				+ "        console.log(\"Withdraw Options selected\");\r\n"
				+ "        break;\r\n"
				+ "        \r\n"
				+ "        default:\r\n"
				+ "        console.log(\"Invalid Option Selected\");\r\n"
				+ "        \r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "console.log(\"UPDATED BALANCE \" , balance);\r\n"
				+ "\r\n"
				+ "console.log(\"----------------------------------\");\r\n"
				+ "\r\n"
				+ "// for loop for last 5 transactions\r\n"
				+ "\r\n"
				+ "let transactions = [\"Deposit 5000\", \"WithdrawAmount 2000\", \"Deposit 4000\", \"Deposit 3000\", \"WithdraAmount 10000\"];\r\n"
				+ "console.log(\"This is Last 5 transactions: \");\r\n"
				+ "\r\n"
				+ "for(let i=0; i < transactions.length; i++)\r\n"
				+ "{\r\n"
				+ "    console.log(transactions[i]);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "// While Loop login Attempts(limited Attempts)\r\n"
				+ "\r\n"
				+ "let attepmts = 0;\r\n"
				+ "\r\n"
				+ "while(attepmts < 5)\r\n"
				+ "{\r\n"
				+ "   console.log(\"Login Attempts: \", attepmts + 1);\r\n"
				+ "   attepmts++;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "console.log(\"MAX attempts REACHED\");\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "");
	}
	
	public static void main(String[]args)
	{
		Js Con=new Js();
	}

}
